import { Inter } from "next/font/google";
import "./globals.css";

//Components
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dada Saya Sakit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-4">
          <Navigation />
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
